sudo: required
language: python
python:
- "2.7"
services:
  - docker
script: ./run_tests.sh
before_install:
  - docker pull ros:melodic
  - docker run ros:melodic /bin/sh "source /opt/ros/melodic/setup.bash"
install:
  - pip install -r requirements.txt
notifications:
  email:
    on_success: never
    on_failure: always
