sudo: required
language: python
python:
- "2.7"
services:
  - docker
before_install:
  - docker pull ros:melodic
  - docker run -it ros:melodic /bin/bash
  - source /opt/ros/kinetic/setup.bash
  - exit
install:
  - pip install -r requirements.txt
script: ./run_tests.sh
notifications:
  email:
    on_success: never
    on_failure: always
